#!/bin/sh
cd "$(dirname "$0")/.."

echo "Starting containers..."
docker compose up -d

echo "Waiting for DB to be healthy..."
until [ "$(docker inspect -f '{{.State.Health.Status}}' weather_scraping-db-1)" = "healthy" ]; do
    printf "."
    sleep 1
done

echo ""
echo "All containers up!"
docker compose ps