"""initial PostgreSQL migration

Revision ID: 2e589b81eeb8
Revises: 
Create Date: 2026-08-13 09:44:34.643625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e589b81eeb8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('real_feel', sa.Float(), nullable=False),
    sa.Column('weather_condition', sa.String(length=255), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('wind_speed', sa.Float(), nullable=False),
    sa.Column('wind_direction', sa.String(length=10), nullable=False),
    sa.Column('visibility', sa.Float(), nullable=False),
    sa.Column('max_uv_index', sa.Float(), nullable=False),
    sa.Column('dew_point', sa.Float(), nullable=False),
    sa.Column('pressure', sa.Float(), nullable=False),
    sa.Column('cloud_cover', sa.Float(), nullable=False),
    sa.Column('cloud_ceiling', sa.Float(), nullable=False),
    sa.Column('precipitation', sa.Float(), nullable=False),
    sa.Column('rain', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_records')
    # ### end Alembic commands ###
